name: Build Pokemon Brisk Emerald

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            libpng-dev \
            gcc-arm-none-eabi \
            binutils-arm-none-eabi

      - name: Build Emerald
        run: make -j$(nproc)

      - name: Rename ROM
        run: |
          find . -maxdepth 3 -type f -name "*.gba" -print
